MyTvTime/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using MyTvTime.Data;
using MyTvTime.Models;
using Newtonsoft.Json;
using RestSharp;

namespace MyTvTime.Controllers
{
    public class MoviesController : Controller
    {
        private readonly TVContext db;
        private readonly int numMoviesToAdd = 5;

        public MoviesController(TVContext context)
        {
            db = context;
        }

        public async Task GenerateGenresSelectList()
        {
            List<SelectListItem> genresSelectList = new List<SelectListItem>();
          //  genresSelectList.Add(new SelectListItem("", "-1"));
            var allGenres = await (from g in db.Genre select g).ToListAsync();
            foreach (Genre g in allGenres)
                genresSelectList.Add(new SelectListItem(g.Name, g.ID.ToString()));
            ViewData["GenresSelectList"] = genresSelectList;
        }

        // GET: Movies
        public async Task<IActionResult> Index(string title, string language, int releaseYear, string genre)
        {
            var movies = from m in db.Movie select m;

            await GenerateGenresSelectList();

            //No search at all.
            if (string.IsNullOrEmpty(title) && string.IsNullOrEmpty(language) && releaseYear == 0 && string.IsNullOrEmpty(genre))
                return View(await movies.ToListAsync());

            //Search by name was used.
            if (!string.IsNullOrWhiteSpace(title))
            {
                //Show the movies found in our DB And if nothing was found automatically show results from IMDB.
                movies = movies.Where(x => x.Name.Contains(title));
                var moviesRes = await movies.ToListAsync();
                if (!moviesRes.Any())
                {
                    ViewData["isIMDB"] = true;
                    return View(await SearchIMDBAsync(title));
                }
            }
            
            //If more searches were applied further filter the results (Works only on results from our DB).
            if (!string.IsNullOrWhiteSpace(language))
                movies = movies.Where(x => x.Language.Contains(language));
            if (releaseYear > 0)
                movies = movies.Where(x => x.ReleaseDate.Year.Equals(releaseYear));

            int genreID = int.TryParse(genre, out genreID) ? genreID : -1;
            if (genreID != -1)
                movies = from m in movies join g in db.MovieGenres on m.ID equals g.MovieID where g.GenreID == genreID select m;

            List<Movie> res = await movies.ToListAsync();


            return View(res);
        }

        public async Task<IActionResult> IndexIMDB(string title)
        // GET: Movies
        
        {
            ViewData["IsUserAdmin"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value;

            await GenerateGenresSelectList();

            ViewData["isIMDB"] = true;

            if (string.IsNullOrEmpty(title))
                return View("Index", new List<Movie>());
            return View("Index", await SearchIMDBAsync(title));
        }

        public async Task<IActionResult> WatchList() {
            int userId = HttpContext.User.Identity.IsAuthenticated ? int.Parse(((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value) : 0;

            var myWatchList = await db.UserMovie.Where(um => um.UserId == userId).Include(m => m.Movie).Include(m=> m.Movie.Genres).ToListAsync();

            var MoviesId = myWatchList.Select(m => m.MovieId).ToArray();
            var Genre = myWatchList.Select(um => um.Movie.Genres);
            var GenreDistinct = Genre.SelectMany(item => item).Distinct().ToArray();
            var GenereCount = GenreDistinct.GroupBy(item => item.GenreID).Select(group => new
            {
                GenreId = group.Key,
                Count = group.Count()
            }).OrderByDescending(x=>x.Count).ToArray();

            if (GenereCount.Length > 1)
            {
                var RecommendedMovies = db.MovieGenres.Include(m => m.Movie).Where(mg => (mg.GenreID == GenereCount[0].GenreId || mg.GenreID == GenereCount[1].GenreId) && !MoviesId.Contains(mg.MovieID)).Select(mg => mg.Movie).Distinct();

                ViewBag.RecommendedMovies = RecommendedMovies;
            }

            return View(myWatchList);
        }

       

        public async Task<List<Movie>> SearchIMDBAsync(string title)
        {
            List<Movie> movies = new List<Movie>();
            
            for (int i = 1; i <= 3; i++)
            {
                //Send the request through the API.
                var client = new RestClient("https://movie-database-imdb-alternative.p.rapidapi.com/?s=" + title + "&page=" + i + "&r=json&type=movie");
                var request = new RestRequest(Method.GET);
                request.AddHeader("x-rapidapi-key", "93f2bbe6bdmsh4a12d4d9e5b771dp14b702jsn8bc0f393b0ca");
                request.AddHeader("x-rapidapi-host", "movie-database-imdb-alternative.p.rapidapi.com");
                var response = await client.ExecuteAsync(request);
                if(response.IsSuccessful)
				{
                    SearchMovieResultRoot resultsRoot = JsonConvert.DeserializeObject<SearchMovieResultRoot>(response.Content);
                    if(resultsRoot.totalResults != null) {
                        if (i * 10 > int.Parse(resultsRoot.totalResults))
                            i = 4;

                        foreach (SearchMovieResult result in resultsRoot.Search)
                            movies.Add(new Movie { ID = -1, Name = result.Title, IMDBID = result.imdbID, ImageURL = result.Poster });
                    }
                }
            }

            return movies;
        }
        
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await db.Movie.Where(m => m.ID == id).Include(x => x.Comments).ThenInclude(x => x.User).Include(x => x.Genres).ThenInclude(x => x.Genre)
                .FirstOrDefaultAsync();
            if (movie == null)
            {
                return NotFound();
            }
            int userId = HttpContext.User.Identity.IsAuthenticated ? int.Parse(((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value) : 0;
           
            var movieWatched = await db.UserMovie.FirstOrDefaultAsync(um => (um.MovieId == id && um.UserId == userId));

            ViewData["UserID"] = userId;

            if (movieWatched == null)
            {
                ViewBag.inWatchList = false;
            } else
            {
                ViewBag.inWatchList = true;
            }

            return View(movie);
        }

        public async Task<IActionResult> AddMovieAsync(string IMDBID)
        {
            var checkMovie = from m in db.Movie where m.IMDBID == IMDBID select m;
            if (checkMovie.Any())
            {
                return RedirectToAction("Details", new { id = checkMovie.First().ID });
             }
            var client = new RestClient("https://movie-database-imdb-alternative.p.rapidapi.com/?i=" + IMDBID +" &r=json&type=movie&plot=short");
            var request = new RestRequest(Method.GET);
            request.AddHeader("x-rapidapi-key", "93f2bbe6bdmsh4a12d4d9e5b771dp14b702jsn8bc0f393b0ca");
            request.AddHeader("x-rapidapi-host", "movie-database-imdb-alternative.p.rapidapi.com");
            var response = await client.ExecuteAsync(request);

            if (response.IsSuccessful)
            {
                IMDBMovieDetails movieDetails = JsonConvert.DeserializeObject<IMDBMovieDetails>(response.Content);

                Movie m = new Movie
                {
                    IMDBID = movieDetails.imdbID,
                    Name = movieDetails.Title,
                    ReleaseDate = movieDetails.GetReleaseDateTime(),
                    Runtime = movieDetails.GetRuntimeAsInt(),
                    Description = movieDetails.Plot,
                    Language = movieDetails.GetFirstLanguage(),
                    ImageURL = movieDetails.Poster
                };

                await db.Movie.AddAsync(m);
                await db.SaveChangesAsync();

                string[] genres = movieDetails.GetGenresArray();
                foreach (string s in genres)
                {
                    var genreFromDB = from g in db.Genre where (g.Name == s) select g;
                    if (!genreFromDB.Any())
                    {
                        await db.Genre.AddAsync(new Genre { Name = s });
                        await db.SaveChangesAsync();
                        genreFromDB = from g in db.Genre where (g.Name == s) select g;
                    }
                    Genre genre = genreFromDB.First();
                    var newMovieGenre = new MovieGenres { MovieID = m.ID, GenreID = genre.ID };
                    await db.MovieGenres.AddAsync(newMovieGenre);
                    await db.SaveChangesAsync();
                }
                await db.SaveChangesAsync();

                return  RedirectToAction("Details", new { id = m.ID });
            }
            return Redirect("~/Error");
        }
 
        [HttpPost, ActionName("AddToWatchList")]
        public async Task<IActionResult> AddToWatchList(string movieId, string isExist)
		{
            int userId = HttpContext.User.Identity.IsAuthenticated ? int.Parse(((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value) : 0;
            if (isExist == "0")
            {
                try
                {
                    await db.UserMovie.AddAsync(new UserMovie { MovieId = int.Parse(movieId), UserId = userId });

MyTvTime/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyTvTime.Data;
using MyTvTime.Models;
using System.Security.Claims;

namespace MyTvTime.Controllers
{
    public class UsersController : Controller
    {
        private readonly TVContext _context;

        public UsersController(TVContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(string username, string country)
        {
            if(!Convert.ToBoolean(((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value))
            {
                return RedirectToAction(nameof(AuthController.AccessDenied), "Auth");
            }
            var users = from u in _context.User select u;

            if(!string.IsNullOrWhiteSpace(username))
			{
                users= users.Where(u => u.username == username);
			}

            if(!string.IsNullOrWhiteSpace(country))
			{
                users= users.Where(u => u.country == country);
            }

            List<User> res = await users.ToListAsync();
            return View(res);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["IsUserAdmin"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value;
            ViewData["UserId"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value;
            if (id == null)
            {
                if (HttpContext.User.Identity.IsAuthenticated)
                {
                    var identity = ((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value;
                    id = Int32.Parse(identity);
                }
                else
                {
                    return NotFound();
                }
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value;
            ViewData["IsUserAdmin"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value;
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,username,password,email,birthdate,country,language,sex, isAdmin")] User user)
        {
            ViewData["IsUserAdmin"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value;
            ViewData["UserId"] = ((ClaimsIdentity)User.Identity).FindFirst(type: "UserId").Value;
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IsUserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Details",user);
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!Convert.ToBoolean(((ClaimsIdentity)User.Identity).FindFirst(type: "isAdmin").Value))
            {
                return RedirectToAction(nameof(AuthController.AccessDenied), "Auth");
            }
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
          
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        
        }

        private bool IsUserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

MyTvTime/Views/Movies/Details.cshtml
@model MyTvTime.Models.Movie

@{
	ViewData["Title"] = Model.Name;
}

<style>
	.displayName {
		font-weight: bold;
		display: inline-block;
	}

	.data {
		display: inline-block;
	}

	.description {
		max-width: 50%;
		margin: 20px 20px 20px;
		color: gray;
		display: inline-block;
	}

	img {
		display: inline-block;
	}

	.addWatchList {
		background-image: url('https://cdn0.iconfinder.com/data/icons/mix-of-simple-vol-4/57/02-512.png');
		border: none;
		background-repeat: no-repeat;
		background-size: 100% 100%;
		height: 8vh;
		width: 5vw;
		border-radius: 5px;
	}

	.removeWatchList { 
		background-image: url('https://art-tshirt.com/wp-content/uploads/2019/09/FFFFFF.png');
		border: none;
		background-repeat: no-repeat;
		background-size: 100% 100%;
		height: 8vh;
		width: 5vw;
		border-radius: 5px; 

	}


	h4 {
		display: inline-block;
	}
</style>

<div>
	<div>
		<div style="display: inline-block;">
			<form asp-controller="Movies" asp-action="AddToWatchList" method="post">
				<input type="hidden" name="movieId" value="@Html.DisplayFor(model => model.ID)" />
				@if (!ViewBag.inWatchList)
				{
					<input type="hidden" name="isExist" value="0" />
					@:<input type="submit" class="addWatchList" value=" "/>

				}
				else
				{
					<input type="hidden" name="isExist" value="1" />
					@: <input type="submit" class="removeWatchList" value=" " />
				}
			</form>
		</div>
		<h4>@Html.DisplayFor(model => model.Name)</h4>
	</div>
	
	<hr />
	<div>
		<img src="@Model.ImageURL" width="100" />
		<div class="description"> @Model.Description</div>
	</div>

	<div>
		<div class="displayName">
			@Html.DisplayNameFor(model => model.Genres):
		</div>
		<div class="data">
			@foreach (MovieGenres movieGenres in Model.Genres)
			{
				<div class="data">
					@movieGenres.Genre.Name ,
				</div>
			}
		</div>
	</div>
	<div>
		<div class="displayName">@Html.DisplayNameFor(model => model.ReleaseDate):</div>
		<div class="data"> @Model.ReleaseDate.ToShortDateString()</div>
	</div>
	<div>
		<div class="displayName">@Html.DisplayNameFor(model => model.Language):</div>
		<div class="data"> @Model.Language</div>
	</div>
	<div>
		<div class="displayName">@Html.DisplayNameFor(model => model.Runtime):</div>
		<div class="data"> @Model.Runtime</div>
	</div>
</div>
<hr />

<!--Display Comment Section-->
<div>
	<h5>What Other People Think?</h5>
	@if (!Model.Comments.Any())
	{
		<p>Be the first to add a comment.</p>
	}
	else
	{
		<ol>
			@foreach (Comment comment in Model.Comments)
			{
				<li>
					<address>
						<a asp-controller="Users" asp-action="Details" asp-route-id="@comment.UserID">@comment.User.username</a>
					</address>
					<article>
						@comment.Text
					</article>
					@if (comment.UserID == (int)ViewData["UserID"])
					{
						<button id="deleteButton" type="button" class="btn btn-danger" data-toggle="modal" data-id="@comment.ID" data-text="@comment.Text" data-target="#deleteCommentModal">Delete</button>
						<button id="editButton" type="button" class="btn btn-info" data-toggle="modal" data-id="@comment.ID" data-text="@comment.Text" data-target="#editCommentModal">Edit</button>
					}
				</li>
			}
		</ol>
	}
</div>

<!--Add Comment Section-->
<div>
	<form asp-controller="Comments" asp-action="AddComment">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<input name="movieID" value="@Model.ID" hidden />
			<textarea name="commentText" class="form-control" placeholder="Write here..." required></textarea>
		</div>
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-primary" />
		</div>
	</form>
</div>

<!--Delete Comment Modal Section-->
<script type="text/javascript">
	$(document).on('click', '#deleteButton', function () {
		$('#deleteModalCommentText').text($(this).data('text'));
		$('#commentIDToDelete').val($(this).data('id'));
	});
</script>

<div id="deleteCommentModal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Are you sure you want to delete this comment?</h4>
			</div>
			<div class="modal-body">
				<p id="deleteModalCommentText"></p>
			</div>
			<div class="modal-footer">
				<form asp-controller="Comments" asp-action="Delete" method="post">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<input id="commentIDToDelete" type="hidden" name="id" value="" />
					<input type="hidden" name="movieID" value="@Model.ID" />
					<button type="submit" class="btn btn-danger" formaction="/Comments/Delete">Delete</button>
				</form>
			</div>
		</div>
	</div>
</div>

<!--Edit Comment Modal Section-->
<script type="text/javascript">
	$(document).on('click', '#editButton', function () {
		$('#editModalCommentText').val($(this).data('text'));
		$('#commentIDToEdit').val($(this).data('id'));
	});
</script>

<div id="editCommentModal" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Edit Comment</h4>
			</div>
			<div class="modal-body">
				<form asp-controller="Comments" asp-action="Edit">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<input type="hidden" name="movieID" value="@Model.ID" />
						<input id="commentIDToEdit" type="hidden" name="id" value="" />
						<textarea id="editModalCommentText" name="newCommentText" class="form-control" required></textarea>
					</div>
					<div class="form-group">
						<input type="submit" value="Edit" class="btn btn-primary" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div>
	<a asp-action="Index">Back to movies List</a>
</div>

MyTvTime/Views/Movies/Edit.cshtml
@model MyTvTime.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="IMDBID" class="control-label"></label>
                <input asp-for="IMDBID" class="form-control" />
                <span asp-validation-for="IMDBID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MyTvTime/Views/Movies/Index.cshtml
@model IEnumerable<MyTvTime.Models.Movie>

@{
	ViewData["Title"] = "Movies";
	<script type="text/javascript">

		$(document).ready(function () {
			var languages = $('#language');
			var genres = $('#genre');
			var languageSettings = {
				"async": true,
				"crossDomain": true,
				"url": "https://wft-geo-db.p.rapidapi.com/v1/locale/languages?limit=10",
				"method": "GET",
				"headers": {
					"x-rapidapi-host": "wft-geo-db.p.rapidapi.com",
					"x-rapidapi-key": "58193b92e9msh4940fad70ac6d4fp1bfe08jsn592fbe2245b9"
				}
			}
			$.ajax(languageSettings).done(function (response) {
				languages.empty().append($('<option></option>').val('').text('Language'));
				$.each(response.data, function (index, item) {
					languages.append($(`<option></option>`).val(item.name).text(item.name));
				});
			});
		});
	</script>
}

<style>
	input:focus {
		outline: 0;
	}

	.filterInput > input {
		border-radius: 14px;
		text-align: center;
		width: 80%;
		border: 2px solid gray;
	}

	.filterInput > select {
		border-radius: 14px;
		width: 80%;
		border: 2px solid gray;
	}

	.filterButtom {
		border-radius: 14px;
		border: 0px;
		background: #1976d2;
		height: 100%;
		width: 10%;
		color: white;
	}

	.imdbFilter > input {
		border-radius: 14px;
		text-align: center;
		border: 2px solid gray;
	}

	.imdbFilterButtom {
		border-radius: 14px;
		border: 0px;
		background: #1976d2;
		width: 10%;
		color: white;
		margin-left: 5%
	}

	.noMovies {
		width: 100%;
		height: 100%;
		text-align: center;
	}
</style>

<h1>Search Movie</h1>

<form asp-controller="Movies" asp-action="Index" method="get">
	<div class="search-section" style="margin: 50px 0px 25px;">
		<div class="search-field filterInput">
			<input type="text" id="title-field" name="title" placeholder="Title">
		</div>
		<div class="search-field filterInput">
			<select id="language" name="language" class="form-control "></select>
		</div>
		<div class="search-field filterInput">
			<input type="number" name="ReleaseYear" placeholder="Release Year">
		</div>
		<div class="search-field filterInput">
			@Html.DropDownList("genre", ViewData["GenresSelectList"] as List<SelectListItem>, "Genre", new { @class = "form-control" })
		</div>
		<input type="submit" value="Filter" class="filterButtom" />
	</div>
</form>


<form asp-controller="Movies" asp-action="IndexIMDB" method="get">
	<div style="display:flex; height:30px; margin-bottom:50px">
		<div class="imdbFilter">
			<label class="control-label">
				Didn't found what you were looking for?
				Try searching using IMDB.
			</label>
			<input type="text" name="title" placeholder="Title to search on IMDB...">
		</div>
		<input type="submit" value="IMDB Search" class="imdbFilterButtom" />
	</div>

</form>
<hr />

@if (Model.Count() == 0)
{
	<div class="noMovies">
		<p>- No Movie Found -</p>
	</div>
}
else
{
	<div class="container-fluid">
		@if (ViewData["isIMDB"] != null)
		{
			<p>Results from IMDB...</p>
		}
		<div class="row">
			@foreach (var item in Model)
			{
				<div class="col-md-auto" style="width: 20%;">
					<ul style="list-style-type:none">
						<li style="width: 30%;">
							<img src="@item.ImageURL" width="100" style="height: 25vh" />
						</li>
						<li style="text-align: center;width: 70%;">
							@if (item.ID != -1)
							{
							<a asp-action="Details" asp-route-id="@item.ID">@item.Name</a>
							}
							else
							{
							<a asp-action="AddMovie" asp-route-IMDBID="@item.IMDBID">@item.Name</a>
							}
						</li>
					</ul>
				</div>
			}
		</div>
	</div>
}

MyTvTime/Views/Movies/WatchList.cshtml
@{
	ViewData["Title"] = "WatchList";
}

<style>
	.noMovies {
		width: 100%;
		height: 100%;
		text-align: center;
	}

		.noMovies p {
			margin-top: 15%;
			font-weight: bold;
		}

	.moviesList {
		display: flex;
		flex-flow: row wrap;
		width: 100%;
		overflow: auto;
		max-height: 43vh;
	}

	.movieBlock {
		display: inline-block;
		margin-right: 2%;
	}

	.movieImg {
		width: 10vw;
		height: 30vh;
	}

	.movieText {
		width: 10vw;
		font-weight: bold;
		text-align: center;
	}
</style>


<h1>My Watch List</h1>
<hr />
@if (Model.Count == 0)
{
	<div class="noMovies">
		<p>- Add your first movie -</p>
	</div>
}
else
{
	<div class="moviesList">
		@foreach (var item in Model)
		{

			<div class="movieBlock">
				<img src="@item.Movie.ImageURL" class="movieImg" />

				<div class="movieText">
					<a asp-action="Details" asp-route-id="@item.Movie.ID" style="color: black"> @item.Movie.Name </a>
				</div>
			</div>
		}
	</div>
}

@if(ViewBag.RecommendedMovies != null){
<div style="margin-top:2%">
	<h4>Recommended For You</h4>
	<hr />
	<div class="moviesList">

		@foreach (var item in ViewBag.RecommendedMovies)
		{

			<div class="movieBlock">
				<img src="@item.ImageURL" class="movieImg" />

				<div class="movieText">
					<a asp-action="Details" asp-route-id="@item.ID" style="color: black"> @item.Name </a>
				</div>
			</div>
		}
	</div>
</div>
}